services:
  tsl_manager:
    image: eudi-srv-web-trustedlist-manager-py:0.1
    container_name: tsl_manager
    ports:
      - "5000:5000"
    environment:
      SERVICE_URL: "http://127.0.0.1:5000/"
      #Container path, validate vp token
      TRUSTED_CAS_PATH: "/app/certs/CAs"
      VERIFIER: "verifier-backend.eudiw.dev"
      LOG_PATH: "/app/logs"
      #For signing TSL/LoTL XML 
      CERT: "/app/xml_gen/cert.der"
      #For signing TSL/LoTL XML 
      PRIV_KEY: "app/xml_gen/privkey.pem"
      DB_HOST: "host.docker.internal"
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: "trusted_lists"

    # local path : container path
    volumes:
      - ./CAs:/app/certs/CAs
      #Cert and priv key
      - ./cert.der:/app/xml_gen/cert.der
      - ./privkey.pem:/app/xml_gen/privkey.pem




